export const DEFAULT_AUTH_CONFIG = {
  baseUrl: process.env.REACT_APP_AUTH_BASE_URL || 'http://localhost:8080',
  loginEndpoint: '/auth/login',
  refreshEndpoint: '/auth/refresh',
  autoRefresh: true,
  onTokenExpiredRedirect: '/auth/login',
  profileAfterLogin: false,
  profileEndpoint: '/me',
  joinEndpoint: '/auth/join',
  passwordChangeEndpoint: '/auth/password-change',
  passwordResetEndpoint: '/auth/reset-password',
  passwordFindEndpoint: '/auth/password-find',
  logoutEndpoint: '/auth/logout',
  refreshBeforeExpirySec: 30,
}; 